image: eclipse-temurin:17

variables:
  GRADLE_USER_HOME: .gradle

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  auto_cancel:
    on_new_commit: interruptible

build:
  interruptible: true
  script: ./gradlew build --build-cache
  rules:
    - changes:
      - "*.java"
      - "*.kt"
      - "*.kts"
      - "*gradle*"
      - ".gitlab-ci.yml"
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - .gradle/caches/
      - .gradle/wrapper/
  artifacts:
    paths:
      - lib/build/libs/
